This works from image to container creation.

diff --git a/scripts/build_ats_image b/scripts/build_ats_image
--- a/scripts/build_ats_image
+++ b/scripts/build_ats_image
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 script_name=$(basename $0)
-usage="${script_name} \<docker_image_name\>"
+usage="${script_name} \<new_docker_image_name\> \"\<Git User Name\>\" \<git.user@email.com\>"
 
 tmpdir=/tmp/docker_image_create_$$
 
@@ -11,8 +11,10 @@ fail()
   exit 1
 }
 
-[ $# -eq 1 ] || fail "${usage}"
-tag_name=$1
+[ $# -eq 3 ] || fail "${usage}"
+tag_name=$1; shift
+git_username=$1; shift
+git_email=$1; shift
 
 parent_dir=$(dirname $0)
 ats_dockerfile_dir=${parent_dir}/../Dockerfiles/ats
@@ -20,24 +22,20 @@ ats_dockerfile_dir=${parent_dir}/../Dockerfiles/ats
 
 context_dir=${parent_dir}/../docker_context
 [ -d "${context_dir}" ] || fail "Could not find ATS context directory: ${context_dir}"
-if [ "${USER}" != "bneradt" ]
-then
-  gitconfig=${context_dir}/.gitconfig
-  if grep -q "eradt" "${gitconfig}"
-  then
-    fail "Modify ${gitconfig} to have your name and username."
-  fi
-fi
 
+set -x
+set -e
 mkdir -p ${tmpdir}
 cp -rf ${ats_dockerfile_dir}/* ${tmpdir}
-cp ${context_dir}/.* ${tmpdir}
+cp -rf ${context_dir}/.[^.]* ${tmpdir}
 
 cd $tmpdir
 sudo docker build \
   -t ${tag_name} \
   --build-arg "username=${USER}" \
   --build-arg "userid=$(id -u)" \
+  --build-arg "git_username=$git_username" \
+  --build-arg "git_email=$git_email" \
   .
 
 rm -rf $tmpdir
diff --git a/scripts/make_ats_container b/scripts/make_ats_container
--- a/scripts/make_ats_container
+++ b/scripts/make_ats_container
@@ -10,8 +10,9 @@ fail()
 
 set -e
 
-sudo echo "initialize sudo"
-[ $? -eq 0 ] || fail "sudo initialization failed."
+# Verify early that we can run sudo.
+sudo true
+[ $? -eq 0 ] || fail "Running sudo failed."
 
 [ -n "${HOME}" ] || fail "HOME is not set."
 [ $# -eq 2 ] || fail "Not enough parameters: ${usage}"
@@ -23,17 +24,18 @@ sudo docker run \
   --init \
   --cap-add=SYS_PTRACE \
   --network=host \
-  -u ${USER} \
+  -u $(whoami) \
   -d \
   -t \
-  -v ${HOME}/.ssh:/home/${USER}/.ssh:rw \
+  -v ${HOME}/.ssh:/home/$(whoami)/.ssh:rw \
   ${docker_image}
 
 branch_name=${container_name}
-sudo docker exec -u ${USER} ${container_name} "start_ats_project ${branch_name}"
+sudo docker exec -u $(whoami) ${container_name} /home/$(whoami)/bin/start_ats_project ${branch_name}
 
 echo
 echo "Enter the container with:"
-echo "sudo docker exec -u ${USER} ${container_name} /bin/bash"
+echo "sudo docker exec -it -u $(whoami) ${container_name} /bin/bash"
 echo
-echo "tmux session name: ${branch_name}"
+echo "Enter the tmux session with:"
+echo "tmux attach -t ${branch_name}"
